apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-sa
  namespace: gy
  annotations:
    # ACK RRSA（推荐）：配合 Namespace label 注入 OIDC token + ALIBABA_CLOUD_* 环境变量
    # 这里填 RAM Role 的名字（不是 ARN）
    pod-identity.alibabacloud.com/role-name: "go-sa"
    # 兼容：若你的集群/组件使用 ARN 注入，也保留这一条
    alibabacloud.com/ram-role-arn: "acs:ram::1930344476137822:role/go-sa"

imagePullSecrets:
  - name: acr-pull

